---
title: 'Seminoff EPac green turtle Stable Isotope Data Analysis-models only doc'
author: "Lisa Komoroske"
date: '`r Sys.Date()`'
output: word_document
session info: '`sessionInfo(package = NULL)`'  
---

##Setup
```{r setup, echo=FALSE,include=FALSE,message = FALSE}
library(here)
setwd(here("scripts&RMD_files"))
getwd()
```

##Load Required Libraries
```{r libraries, echo=FALSE, include=FALSE}
library(ggplot2)
library(plyr)
library(RColorBrewer)
library(MASS); library(lattice)
#library(lme4); 
library(lmerTest);library(car);library(nlme)
library(MuMIn);library(sjmisc);library(sjPlot)
```

##Read in data
```{r read_data, echo=FALSE,include=FALSE}
data<-read.csv("../Files_local_repo_only/data/CM Isotope Data UPDATED_Jan122017.csv")
#updated 12-20-16 summary files reading in here to reflect new groupings, excluded data etc.
data$Ordered_SITE<-factor(data$Ordered_SITE, levels =c("1-SGR_SBN","3-SDB","4-NGU","6-BMA","7-IPD","8-LOR","9-BLA","11-CIN","12-NAV", "13-DUL","14-PAR","15-MEJ","16-ISL","17-COC","18-GOR","19-IGP","20-IGE","21-IGD","22-IGZ","23-IGN","24-PPE"))

#12-19-16 added: removing problematic sites and questionable values
data_new<-subset(data, Ordered_SITE!="7-IPD" &Ordered_SITE!="8-LOR"&Ordered_SITE!="16-ISL"&Ordered_SITE!="22-IGZ"&Ordered_SITE!="23-IGN")
data_new<-subset(data_new, Percent_N>=5 | is.na(data_new$Percent_N) )
data_new<-subset(data_new, Percent_N<=20 | is.na(data_new$Percent_N) )
data_new$Collect_Date <- strptime(data_new$Collect_Date, "%m/%d/%Y")
data_new$Run_Date <- strptime(data_new$Run_Date, "%m/%d/%Y")
data<-data_new
data_new2<-subset(data_new,Habitat_Type!="oceanic") #exclude oceanic site; just for EDA linear models at end
```

####Hierarchical models: Nitrogen
```{r hier_models_N, echo=FALSE, message=FALSE }
data<-within(data,Ordered_SITE<-relevel(Ordered_SITE, ref="1-SGR_SBN"))
#data<-within(data,Region<-relevel(Region, ref="SC-BC Pac Coast"))

#complete random effects model
N_M0<-lme(d15N~1, random=~1| Region/Ordered_SITE, data=data)
summary(N_M0)
plot(N_M0, which=1:2)
data$N_M0resid = resid(N_M0)
ggplot(data,aes(x=Ordered_SITE,y=N_M0resid))+geom_boxplot()+geom_point()#problem with heteroscedasticity

#null
N_M1.null<-lme(fixed = d15N ~ 1,random = ~1 | Region, data=data)
#Fixed effect of site, with random effect of region
N_M1.0<-lme(d15N~Ordered_SITE,random = ~1 | Region, data=data)
plot(N_M1.0)
data$N_M1.0resid = resid(N_M1.0)
ggplot(data,aes(x=Ordered_SITE,y=N_M1.0resid))+geom_boxplot()+geom_point()
summary(N_M1.0)

N_M1.1<-lme(d15N~Ordered_SITE,random = ~1 | Region, 
        weights=varIdent(form=~1|Ordered_SITE),
        data=data)
plot(N_M1.1)
data$N_M1.1resid = resid(N_M1.1)
data$N_M1.1residstd<-resid(N_M1.1, type="normalized")
ggplot(data,aes(x=Ordered_SITE,y=N_M1.1resid))+geom_boxplot()+geom_point()
ggplot(data,aes(x=Ordered_SITE,y=N_M1.1residstd))+geom_boxplot()+geom_point()
ggplot(data,aes(x=Region,y=N_M1.1resid))+geom_boxplot()+geom_point()
ggplot(data,aes(x=Region,y=N_M1.1residstd))+geom_boxplot()+geom_point()
summary(N_M1.1)

N_M1.2<-lme(d15N~Ordered_SITE,random = ~1 | Region, 
        weights=varIdent(form=~1|Region),
        data=data)
plot(N_M1.2)
data$N_M1.2resid = resid(N_M1.2)
data$N_M1.2residstd<-resid(N_M1.2, type="normalized")
ggplot(data,aes(x=Ordered_SITE,y=N_M1.2resid))+geom_boxplot()+geom_point()
ggplot(data,aes(x=Ordered_SITE,y=N_M1.2residstd))+geom_boxplot()+geom_point()
ggplot(data,aes(x=Region,y=N_M1.2resid))+geom_boxplot()+geom_point()
ggplot(data,aes(x=Region,y=N_M1.2residstd))+geom_boxplot()+geom_point()
summary(N_M1.2)

varRegionSite<-varComb(varIdent(form=~1|Region),varIdent(form=~1|Ordered_SITE))
N_M1.3<-lme(d15N~Ordered_SITE,random = ~1 | Region, 
        weights=varRegionSite,data=data)
plot(N_M1.3)
data$N_M1.3resid = resid(N_M1.3)
data$N_M1.3residstd<-resid(N_M1.3, type="normalized")
ggplot(data,aes(x=Ordered_SITE,y=N_M1.3resid))+geom_boxplot()+geom_point()
ggplot(data,aes(x=Ordered_SITE,y=N_M1.3residstd))+geom_boxplot()+geom_point()
ggplot(data,aes(x=Region,y=N_M1.3resid))+geom_boxplot()+geom_point()
ggplot(data,aes(x=Region,y=N_M1.3residstd))+geom_boxplot()+geom_point()
summary(N_M1.3)

anova(N_M1.null,N_M1.0,N_M1.1,N_M1.2,N_M1.3)
anova(N_M1.1,N_M1.3)
N_mod_selection<-model.sel(N_M1.null,N_M1.0,N_M1.1,N_M1.2,N_M1.3)
N_mod_selection
#Fixed effect of site, with random effect of region/site
#results almost identical if specify site nested in region random effect:
#N_M2.0<-lme(d15N~Ordered_SITE,random = ~1 | Region/Ordered_SITE, data=data)
#N_M2.1<-lme(d15N~Ordered_SITE,random = ~1 | Region/Ordered_SITE, 
        #weights=varIdent(form=~1|Ordered_SITE),
       # data=data)
#N_M2.2<-lme(d15N~Ordered_SITE,random = ~1 | Region/Ordered_SITE, 
       # weights=varIdent(form=~1|Region),
      # data=data)
#summary(N_M2.0)
#summary(N_M2.1)
#summary(N_M2.2)

#Supplemental Figure 2 (code also copied to final figures .rmd file)
vf<-read.csv("../Files_local_repo_only/data/N_M1.1_variancefactors.csv")
levels(vf$Location_Code)
vf$Location_Code<-factor(vf$Location_Code,levels=c("LB","SDB","NGU","BMA","BLA","CIN","NAV","DUL","PAR","MEJ", "PPE", "COC", "GOR","IGE","IGD", "IGP"))
levels(vf$Region)
vf$Region<-factor(vf$Region,levels=c("SoCal-Baja Pacific Coast","Gulf of California"  ,"Central-S. America Pacific Coast","Oceanic" , "East Pacific Islands"   ))         

palette1<-c("firebrick","firebrick","deepskyblue3","deepskyblue3","firebrick","firebrick","firebrick","grey70","firebrick","deepskyblue3","firebrick","firebrick","firebrick","firebrick","firebrick","firebrick")
palette2<-c("forest green","red", "purple","deepskyblue3","orange")
var1<-ggplot(vf,aes(x=Location_Code,y=Var_factor,fill=Location_Code))+geom_bar(stat="identity")+theme_bw()+xlab("Study Site")+ylab("d15N Variance Multiplication Factor")+geom_hline(yintercept=1, linetype="dashed")+scale_fill_manual(values=palette1)+guides(fill=FALSE)

var1+ theme(axis.title.x = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=45, vjust=0.5, size=12),
           axis.title.y = element_text(face="bold", size=14),
           axis.text.y  = element_text(angle=0, vjust=0.5, size=12))

var2<-ggplot(vf,aes(x=Location_Code,y=Var_factor,fill=Region))+geom_point(size=6.5,shape=21)+theme_bw()+xlab("Study Site")+ylab("d15N Variance Multiplication Factor")+geom_hline(yintercept=1, linetype="dashed")+scale_fill_manual(values=palette2)+guides(fill=FALSE)

var2+ theme(axis.title.x = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=45, vjust=0.5, size=12),
           axis.title.y = element_text(face="bold", size=14),
           axis.text.y  = element_text(angle=0, vjust=0.5, size=12))+theme(panel.grid.major.x=element_line(colour="grey75",linetype="dashed"))
```

####Hierarchical models: Carbon
```{r hier_models_C, echo=FALSE, message=FALSE }
#complete random effects model
C_M0<-lme(d13C~1, random=~1| Region/Ordered_SITE, data=data)
summary(C_M0)
plot(C_M0, which=1:2)
data$C_M0resid = resid(C_M0)
ggplot(data,aes(x=Ordered_SITE,y=C_M0resid))+geom_boxplot()+geom_point()#problem with heteroscedasticity

#null
C_M1.null<-lme(fixed = d13C ~ 1,random = ~1 | Region, data=data)
#Fixed effect of site, with random effect of region
C_M1.0<-lme(d13C~Ordered_SITE,random = ~1 | Region, data=data)
plot(C_M1.0)
data$C_M1.0resid = resid(C_M1.0)
ggplot(data,aes(x=Ordered_SITE,y=C_M1.0resid))+geom_boxplot()+geom_point()
summary(C_M1.0)

C_M1.1<-lme(d13C~Ordered_SITE,random = ~1 | Region, 
        weights=varIdent(form=~1|Ordered_SITE),
        data=data)
plot(C_M1.1)
data$C_M1.1resid = resid(C_M1.1)
data$C_M1.1residstd<-resid(C_M1.1, type="normalized")
ggplot(data,aes(x=Ordered_SITE,y=C_M1.1resid))+geom_boxplot()+geom_point()
ggplot(data,aes(x=Ordered_SITE,y=C_M1.1residstd))+geom_boxplot()+geom_point()
ggplot(data,aes(x=Region,y=C_M1.1resid))+geom_boxplot()+geom_point()
ggplot(data,aes(x=Region,y=C_M1.1residstd))+geom_boxplot()+geom_point()
summary(C_M1.1)

C_M1.2<-lme(d13C~Ordered_SITE,random = ~1 | Region, 
        weights=varIdent(form=~1|Region),
        data=data)
plot(C_M1.2)
data$C_M1.2resid = resid(C_M1.2)
data$C_M1.2residstd<-resid(C_M1.2, type="normalized")
ggplot(data,aes(x=Ordered_SITE,y=C_M1.2resid))+geom_boxplot()+geom_point()
ggplot(data,aes(x=Ordered_SITE,y=C_M1.2residstd))+geom_boxplot()+geom_point()
ggplot(data,aes(x=Region,y=C_M1.2resid))+geom_boxplot()+geom_point()
ggplot(data,aes(x=Region,y=C_M1.2residstd))+geom_boxplot()+geom_point()
summary(C_M1.2)

varRegionSite<-varComb(varIdent(form=~1|Region),varIdent(form=~1|Ordered_SITE))
C_M1.3<-lme(d13C~Ordered_SITE,random = ~1 | Region, 
        weights=varRegionSite,data=data)
plot(C_M1.3)
data$C_M1.3resid = resid(C_M1.3)
data$C_M1.3residstd<-resid(C_M1.3, type="normalized")
ggplot(data,aes(x=Ordered_SITE,y=C_M1.3resid))+geom_boxplot()+geom_point()
ggplot(data,aes(x=Ordered_SITE,y=C_M1.3residstd))+geom_boxplot()+geom_point()
ggplot(data,aes(x=Region,y=C_M1.3resid))+geom_boxplot()+geom_point()
ggplot(data,aes(x=Region,y=C_M1.3residstd))+geom_boxplot()+geom_point()
summary(C_M1.3)

anova(C_M1.null,C_M1.0,C_M1.1,C_M1.2,C_M1.3)
anova(C_M1.1,C_M1.3)
C_mod_selection<-model.sel(C_M1.null,C_M1.0,C_M1.1,C_M1.2,C_M1.3)
C_mod_selection

vfC<-read.csv("../Files_local_repo_only/data/C_M1.1_variancefactors.csv")
levels(vfC$Location_Code)
vfC$Location_Code<-factor(vfC$Location_Code,levels=c("LB","SDB","NGU","BMA","BLA","CIN","NAV","DUL","PAR","MEJ", "PPE", "COC", "GOR","IGE","IGD", "IGP"))
levels(vfC$Region)
vfC$Region<-factor(vfC$Region,levels=c("SoCal-Baja Pacific Coast","Gulf of California"  ,"Central-S. America Pacific Coast","Oceanic" , "East Pacific Islands"   ))         

palette3<-c("deepskyblue3","deepskyblue3","deepskyblue3","deepskyblue3","firebrick","grey70","firebrick","grey70","firebrick","firebrick","firebrick","deepskyblue3","firebrick","deepskyblue3","deepskyblue3","deepskyblue3")

var1<-ggplot(vfC,aes(x=Location_Code,y=Var_factor,fill=Location_Code))+geom_bar(stat="identity")+theme_bw()+xlab("Study Site")+ylab("d13C Variance Multiplication Factor")+geom_hline(yintercept=1, linetype="dashed")+scale_fill_manual(values=palette3)+guides(fill=FALSE)

var1+ theme(axis.title.x = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=45, vjust=0.5, size=12),
           axis.title.y = element_text(face="bold", size=14),
           axis.text.y  = element_text(angle=0, vjust=0.5, size=12))

var2<-ggplot(vfC,aes(x=Location_Code,y=Var_factor,fill=Region))+geom_point(size=6.5,shape=21)+theme_bw()+xlab("Study Site")+ylab("d13C Variance Multiplication Factor")+geom_hline(yintercept=1, linetype="dashed")+scale_fill_manual(values=palette2)+guides(fill=FALSE)

var2+ theme(axis.title.x = element_text(face="bold", size=14),
           axis.text.x  = element_text(angle=45, vjust=0.5, size=12),
           axis.title.y = element_text(face="bold", size=14),
           axis.text.y  = element_text(angle=0, vjust=0.5, size=12))+theme(panel.grid.major.x=element_line(colour="grey75",linetype="dashed"))
```

#### Linear Models   
Note: these are now just anovas bc took out turtle body size due to missing data from some sites. Just left these in from EDA in case turns out useful to look at fanning, etc.  
```{r models, echo=FALSE, message=FALSE }
summary(data)
data$Ordered_SITE<-factor(data$Ordered_SITE)
table(data$Ordered_SITE)

#Linear models-For each region seperately
summary(data_new2$Region)
SC<-subset(data_new2, Region=="SC-BC Pac Coast")     
GC<-subset(data_new2, Region=="Gulf of Cal")
CSC<-subset(data_new2, Region== "Cen-SoAm Pac Coast") 
EPI<- subset(data_new2, Region== "EPac Islands")

SC_Nm2<-aov(data=SC, d15N~Ordered_SITE)
GC_Nm2<-aov(data=GC, d15N~Ordered_SITE)
CSC_Nm2<-aov(data=CSC, d15N~Ordered_SITE)
EPI_Nm2<-aov(data=EPI, d15N~Ordered_SITE)

summary(SC_Nm2)
par(mfrow=c(2, 1))
plot(SC_Nm2, which=1:2)
dev.off()
SC$Nresid = resid(SC_Nm2)
ggplot(SC,aes(x=Ordered_SITE,y=Nresid))+geom_boxplot()+geom_point()

summary(GC_Nm2)
par(mfrow=c(2, 1))
plot(GC_Nm2, which=1:2)
dev.off()
GC$Nresid = resid(GC_Nm2)
ggplot(GC,aes(x=Ordered_SITE,y=Nresid))+geom_boxplot()+geom_point()

summary(CSC_Nm2)
par(mfrow=c(2, 1))
plot(CSC_Nm2, which=1:2)
dev.off()
CSC$Nresid = resid(CSC_Nm2)
ggplot(CSC,aes(x=Ordered_SITE,y=Nresid))+geom_boxplot()+geom_point()

summary(EPI_Nm2)
par(mfrow=c(2, 1))
plot(EPI_Nm2, which=1:2)
dev.off()
EPI$Nresid = resid(EPI_Nm2)
ggplot(EPI,aes(x=Ordered_SITE,y=Nresid))+geom_boxplot()+geom_point()

#-------
#Carbon 

SC_Cm2<-aov(data=SC, d13C~Ordered_SITE)
GC_Cm2<-aov(data=GC, d13C~Ordered_SITE)
CSC_Cm2<-aov(data=CSC, d13C~Ordered_SITE)
EPI_Cm2<-aov(data=EPI, d13C~Ordered_SITE)


summary(SC_Cm2)
par(mfrow=c(2, 1))
plot(SC_Cm2, which=1:2)
dev.off()
SC$Cresid = resid(SC_Cm2)
ggplot(SC,aes(x=Ordered_SITE,y=Cresid))+geom_boxplot()+geom_point()

summary(GC_Cm2)
par(mfrow=c(2, 1))
plot(GC_Cm2, which=1:2)
dev.off()
GC$Cresid = resid(GC_Cm2)
ggplot(GC,aes(x=Ordered_SITE,y=Cresid))+geom_boxplot()+geom_point()

summary(CSC_Cm2)
par(mfrow=c(2, 1))
plot(CSC_Cm2, which=1:2)
dev.off()
CSC$Cresid = resid(CSC_Cm2)
ggplot(CSC,aes(x=Ordered_SITE,y=Cresid))+geom_boxplot()+geom_point() #moderate fanning, be aware-come back to

summary(EPI_Cm2)
par(mfrow=c(2, 1))
plot(EPI_Cm2, which=1:2)
dev.off()
EPI$Cresid = resid(EPI_Cm2)
ggplot(EPI,aes(x=Ordered_SITE,y=Cresid))+geom_boxplot()+geom_point()

```